### PR TITLE
Moving dotnet-watch to netcoreapp1.0

### PR DESCRIPTION
**Pull request by moozzyk**

### CODE REVIEW

**Comment by victorhurdugaci** [comment]
Looks good :shipit:

**Comment by pakrym** [comment]
Check if it run's `dotnet restore` without `--infer-runtimes` during `.\build`, :shipit: otherwise

**Comment by moozzyk** [comment]
@pakrym - no --infer-runtimes (yay, I spelled it correctly the first time)
```
info: Exec
info:   program: dotnet
info:   commandline: restore
info:   workingdir: C:\Source\dotnet-watch
```

**Pull request closed without merging**
