### PR TITLE
Remove `Microsoft.DotNet.Watcher.Tools.FunctionalTests.NoDepsAppTestsRestartProcessThatTerminatesAfterFileChange`

### PR DESCRIPTION
**Pull request by dougbu**
- test is not reliable (95% success rate)
- should be restored as part of #98

### CODE REVIEW

**Comment by dougbu** [comment]
/cc @muratg 
Didn't mean to push this into `dev`. I've reverted that 'til this PR is approved.

**Comment by muratg** [comment]
@dougbu Can't we just disable for now?

**Comment by dougbu** [comment]
:up::date:

**Comment by victorhurdugaci** [comment]
:shipit:

**Comment by dougbu** [comment]
dc9fead

**Pull request closed without merging**
