### PR TITLE
Add dotnet-user-secrets

### PR DESCRIPTION
**Pull request by natemcmaster**
Moving day! Incoming content from https://github.com/aspnet/UserSecrets/pull/107

cc @Eilon can we rename repo to "DotNetTools"?
cc @muratg @glennc

### CODE REVIEW

**Comment by Eilon** [comment]
Let me know once everything is good to go and I'll rename this repo.

**Comment by natemcmaster** [comment]
Ok, I'll let you know when all the dust has settled as we shuffle bits around.

**Comment by natemcmaster** [comment]
@Eilon all the changes are merged now. You can go ahead and rename the repo now.

**Comment by Eilon** [comment]
Repo renamed.

**Pull request merged**
